
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: vidly_web:1
    ports:
      - 80:80
    restart: unless-stopped
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.pro
    image: vidly_api:1
    ports:
      - 80:3001
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    command: /bin/sh -c 'npm run db:up && npm start'
  db:
    image: mongo:4.0-xenial
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - vidly:/data/db
volumes:
  vidly: